# curl "http://localhost:9999/login" -X POST -d 'username=geektutu&password=1234'
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

userName=thc&password=1234

###

###
GET http://localhost:8080/v1/hello

###
GET localhost:8080/index

###
GET localhost:8080

###
GET http://localhost:8080/hello/thc

###
POST http://localhost:8080/userInfo
Content-Type: application/json

{"id": "hhhhh"}

###
GET http://localhost:8080/assets/css/thc.css